; This file was automatically generated by ScriptHubImporter.py
this.CazrinLibraryOfLoreHandler.booksCollected := New GameObjectStructure(this.CazrinLibraryOfLoreHandler,"Int", [0xac])
this.CazrinLibraryOfLoreHandler.booksCollectedThisAdventure := New GameObjectStructure(this.CazrinLibraryOfLoreHandler,"Int", [0xa8])
this.CazrinLibraryOfLoreHandler.maxBookDivisor := New GameObjectStructure(this.CazrinLibraryOfLoreHandler,"Int", [0xb0])
